### ISSUE TITLE
isprime(n) allocates

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/Primes.jl#125]
See [this discourse comment](https://discourse.julialang.org/t/mysterious-allocations-in-nested-scalar-loops/90380/3?u=stevengj).

It seems like this could be fixed with a little refactoring.  Instead of having [`witnesses(n)`](https://github.com/JuliaMath/Primes.jl/blob/fde566c12c3c1d5418d6d2e67087ed9cb2a11db0/src/Primes.jl#L237-L247) return a variably sized tuple (which is not type stable), it would be better to inline this into `isprime` and do something like:
```jl
return n < 4294967296  ? checkwitnesses(n, _witnesses(UInt64(n))) :
        n < 2152302898747   ? checkwitnesses(n, (2, 3, 5, 7, 11)) :
        n < 3474749660383   ? checkwitnesses(n, (2, 3, 5, 7, 11, 13)):
                              checkwitnesses(n, (2, 325, 9375, 28178, 450775, 9780504, 1795265022))
```
where `checkwitnesses(n, witnesses)` is simply [this loop](https://github.com/JuliaMath/Primes.jl/blob/fde566c12c3c1d5418d6d2e67087ed9cb2a11db0/src/Primes.jl#L178-L190) refactored into a function.

**Comment by oscardssmith** [comment]
it can. I've done that refactoring in a local branch and never bothered to pr it.

**Comment by oscardssmith** [comment]
this is fixed
