### ISSUE TITLE
Should factor be renamed?

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/Primes.jl#15]
@simonbyrne mentioned in #13 that if we were doing this from scratch, he would have suggested `primefactor` in lieu of `factor` as it's more immediately descriptive. While we may not be doing things from scratch, we are in a situation in which we could make changes as needed. As such, I figured we should discuss this a bit.

I see three potential courses of action for `factor` in particular:

1. Leave it as-is and continue to export it
2. Deprecate it in favor of another name, e.g. `primefactor`
3. Leave it unexported, so one always calls `Primes.factor` (which itself is descriptive)

Surely there are other options as well. What does everyone think?

**Comment by tkelman** [comment]
2 vs 3 are pretty close to equivalent as far as I'm concerned

**Comment by ararslan** [comment]
I think they'd differ from an average end user's point of view, would they not? Maybe it's just me, but sometimes when I use something that isn't exported it makes me wonder whether I'm actually supposed to be using it directly. That said, I have no strong opinions about 2 vs. 3 (or 1, for that matter).

**Comment by ararslan** [comment]
Well, barring any documentation that explicitly says, "This isn't exported so call it like `X.y`."

**Comment by mschauer** [comment]
> but sometimes when I use something that isn't exported it makes me wonder whether I'm actually supposed to be using it directly

This something to keep an eye on, but I think a statement like "provides these functions... which are not exported because of ..." which is contained in the documents clears it up.

**Comment by tkelman** [comment]
There's a somewhat informal convention that if something is documented that it's supposed to be called in a qualified way (like everything under `Profile` in base) then it's treated as public and okay. If it's not externally documented as "you should call this unexported function as `Module.name`" then you maybe shouldn't because it's subject to change.

**Comment by rfourquet** [comment]
I vote for option 1. For numbers, if there are other kind of factorizations, they are I think nowhere close to prime factorization in popularity, so I think there is no ambiguity. For reference, the following systems all use `factor` for prime factorization of integers (or irreducible polynomials for polynomial factorization): sagemath, pari, nemo (a Julia package). 

As a side note, I wonder if `factor` should be defined in base as a generic function, to allow independant packages to extend it.

**Comment by ararslan** [comment]
@rfourquet Yeah, Matlab uses `factor` in this case as well. It's pretty standard.

As such, I think leaving it unexported (option 3) might be the best compromise, since it's still called `factor` but you have the benefit of having a descriptive module name prepended (`Primes.factor`). You can always fully import it anyway (`import Primes: factor`), as we currently do in the tests, so it can be just `factor` if the user prefers.

So... I guess I vote for option 3.

**Comment by ararslan** [comment]
I'd be interested to hear what @simonbyrne thinks of this. :smile:

**Comment by simonbyrne** [comment]
I would lean toward option 1.

**Comment by ararslan** [comment]
So we have 2 for 1 and 1 for 2. How about @tkelman and @mschauer?

**Comment by tkelman** [comment]
Is 1 the same as 3? I'd be weakly against exporting a `factor` from this package but don't mind any other option.

**Comment by ararslan** [comment]
I was totally not clear. Edited the original post. Just in case it's still unclear:

1. `factor` exported
2. `primefactor` exported
3. `factor` not exported

**Comment by tkelman** [comment]
Oh I thought the exports were removed.

**Comment by ararslan** [comment]
For 0.4 they are. Currently we export for 0.5.

**Comment by tkelman** [comment]
`if isdefined(Base,:isprime)` will be true until the deprecations get deleted, and that won't be until 0.6-dev or 0.6-pre

**Comment by ararslan** [comment]
Right, I knew it would be true until the deprecations were removed, but I definitely didn't realize it'd be that long before they're removed. So in terms of actual releases, they'll be deprecated throughout the 0.5 release series and removed in the 0.6 release? I guess no exporting for quite a while then.
