### ISSUE TITLE
BoundsError when trying primes with lo <= 0 and hi >= 7

### ISSUE THREAD

**Issue by motjuste** [JuliaMath/Primes.jl#25]
Hey!

`primes(lo::Int, hi::Int)` fails when `lo <= 0` and `hi >= 7`

Probably a check in `wheel_index(n)` for `n <= 1` to return `0` would work, assuming no negative primes. 
Or, disallowing `lo <= 0` as done in `primesmask(lo::Int, hi::Int)`.

Here are the demos:
```
julia> Primes.primes(0, 6)
3-element Array{Int64,1}:
 2
 3
 5

julia> Primes.primes(0, 7)
ERROR: BoundsError: attempt to access 31-element Array{Int64,1}:
 0
 0
 0
 0
 0
 0
 0
 1
 1
 1
 1
 2
 2
 3
 3
 3
 3
 4
 4
 5
 5
 5
 5
 6
 6
 6
 6
 6
 6
 7
 7
  at index [0]
 in primes at /Users/myrmidon/.julia/v0.4/Primes/src/Primes.jl:124
```

**Comment by ararslan** [comment]
cc @pabloferz

**Comment by pabloferz** [comment]
Should be solved with https://github.com/JuliaMath/Primes.jl/pull/26
