### ISSUE TITLE
Perfecting documentation

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/Primes.jl#32]
I recently set up documentation for this package using Documenter.jl. That worked well, though there are a couple of odd issues:
- All functions are listed with the prefix `Base`. This is likely because, even as of Julia 0.6-dev, `isdefined(Base, :isprime)` is `true`. Not sure what we can do about this.
- The "latest" page works, but "stable" does not; it's a 404. Is this because there hasn't been a tagged version since Documenter has been added?

**Comment by rfourquet** [comment]
As of now, the "latest" page works, and all functions are listed with `Primes` prefix in the "latest" docs, but not in "stable"... Closing as it seems there is nothing we can do, except for waiting.
