### ISSUE TITLE
Totient

### ISSUE THREAD

**Issue by TotalVerb** [JuliaMath/Primes.jl#36]
In certain situations, it is nice to have a totient function. I have a naive implementation below, but I'm not very familiar with the theory and so perhaps someone else can suggest a better one.

```julia
function totient(n::Integer)
    if iszero(n)
        throw(ArgumentError("ϕ(0) is not defined"))
    end
    result = one(n)
    for (p, k) in factor(abs(n))
        result *= p^(k-1) * (p - 1)
    end
    result
end
```

**Comment by rfourquet** [comment]
This seems to be a reasonable implementation, so you could simply issue a PR, and anyone is free to improve it later on.
