### ISSUE TITLE
factor a not very big number takes forever

### ISSUE THREAD

**Issue by ixzh** [JuliaMath/Primes.jl#91]
using Primes;
factor(-52150815751994411270420247094986245419003171173880)

takes forever to compute. Any idea?

**Comment by oscardssmith** [comment]
This appears to be a dup of https://github.com/JuliaMath/Primes.jl/issues/49. The good news is that this should be pretty easy to fix. The bad news is that the pull request that would have helped seems to have stalled out in 2017 :(

**Comment by ixzh** [comment]
> This appears to be a dup of #49. The good news is that this should be pretty easy to fix. The bad news is that the pull request that would have helped seems to have stalled out in 2017 :(

**Comment by ixzh** [comment]
switched to Nemo.. works great
